
#changing the server port
server:
  port: '8888'

#db specific properties
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/cab_booking'
    username: postgres
    password: postgres

#ORM s/w specific properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: 'ANT_PATH_MATCHER'

#Cutsom path for API docs
springdoc:
  api-docs:
    path: '/cab-booking-openapi'